language: node_js
cache: npm

#before_install:
#install:
#  -npm install
#before_script:
script:
  -npm run build
#after_success:
#after_failure:
#after_script:
#before_deploy:
deploy:
  provider: pages
  local-dir: ./build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release
#after_deploy:


#branches:
#  only:
#  - release
#gemfile:
#  - gemfiles/gh-pages.gemfile
#script:
#  - JEKYLL_ENV=production bundle exec jekyll build --destination site
#deploy:
#  provider: pages
#  local-dir: ./site
#  target-branch: master
#  email: deploy@travis-ci.org
#  name: Deployment Bot
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  on:
#    branch: release
